name: pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm bootstrap

      - name: Build VuePress site
        run: pnpm db

      - name: Push
        run: sh test.sh

      - name: clean dist
        run: rm -rf dist

      - name: mkdir dist
        run: mkdir dist && mkdir dist/docs

      - name: move to dist
        run: mv docs/dist/* dist/docs

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
